### ISSUE TITLE
2.0 Final Release

### ISSUE THREAD

**Issue by samualjacksonau** [smmorneau/tour-of-heroes#5]
Hi,

Is there any plan to update the code for 2.0 Final Release?

**Comment by smmorneau** [comment]
Hi @samualjacksonau, yes I plan to update to the final release in the next month or so.

**Comment by samualjacksonau** [comment]
Thank you, that would be awesome!

**Comment by smmorneau** [comment]
@samualjacksonau Upgraded to [2.0 Final Release](https://github.com/smmorneau/tour-of-heroes/releases/tag/v2.0).
